[build]
  publish = "public"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  external_node_modules = ["@sparticuz/chromium", "sharp"]
  included_files = ["node_modules/@sparticuz/chromium/bin/**"]

[[redirects]]
  from = "/"
  to = "/.netlify/functions/screenshot"
  status = 200
  force = true
